REACTIVATION_1_QUEUE_NAME = "reactivation_push_1"
REACTIVATION_2_QUEUE_NAME = "reactivation_push_2"
REACTIVATION_3_QUEUE_NAME = "reactivation_push_3"
PARTNER_INSTALLED_APP_QUEUE_NAME = "partner_installed_app_push"
PARTNER_WAITING_QUEUE_NAME = "partner_waiting_push"
PARTNER_ANSWERED_QUEUE_NAME = "partner_answered_push"
PARTNER_NOT_INSTALLED_QUEUE_NAME = "partner_not_installed_push"
LOST_ONBO_QUEUE_NAME = "lost_onbo_push"
LOST_FIRST_QUESTION_QUEUE_NAME = "lost_first_question_push"
STREAK_1_QUEUE_NAME = "streak_1_push"
ANNIVERSARY_QUEUE_NAME = "anniversary_push"
QUESTION_REACTION_QUEUE_NAME = "question_reaction_push"

ANALYTICS_SEND_PUSH_SEND_QUEUE_NAME = "analytics_send_push_send"
